"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from "react";
import { api } from "@/lib/api/client";
import type { TradePlan } from "@/lib/api/types";
import { Panel } from "../ui";
export type Fib = { direction:string;swing_low:string;swing_high:string;levels:Record<string,number> };
export type Range = { range_low:string;range_high:string };
export function FibRangeEditor({plan,onChange}:{plan:TradePlan|null;onChange:(fib:Fib|null,range:Range|null)=>void}){const [fib,setFib]=useState<Fib|null>(null),[range,setRange]=useState<Range|null>(null),[message,setMessage]=useState("");useEffect(()=>{if(!plan){setFib(null);setRange(null);onChange(null,null);return}Promise.all([api.getFibs(plan.id),api.getRanges(plan.id)]).then(([f,r])=>{const nextFib=(f[0]as Fib|undefined)??null,nextRange=(r[0]as Range|undefined)??null;setFib(nextFib);setRange(nextRange);onChange(nextFib,nextRange)}).catch(()=>{setFib(null);setRange(null);onChange(null,null)})},[plan]);const saveFib=async()=>{if(!plan||!fib)return;try{const next=await api.putFib(plan.id,fib)as Fib;setFib(next);onChange(next,range);setMessage("Fib saved")}catch(e){setMessage(e instanceof Error?e.message:"Fib could not save")}};const saveRange=async()=>{if(!plan||!range)return;try{const next=await api.putRange(plan.id,range)as Range;setRange(next);onChange(fib,next);setMessage("Range saved")}catch(e){setMessage(e instanceof Error?e.message:"Range could not save")}};const setF=(k:string,v:string)=>setFib(x=>({...x??{direction:"LONG",swing_low:"",swing_high:"",levels:{}},[k]:v}));const setR=(k:string,v:string)=>setRange(x=>({...x??{range_low:"",range_high:""},[k]:v}));return <Panel title="Fib / range" kicker="PERSISTED STRUCTURE">{plan?<><div className="grid grid-cols-3 gap-2"><select value={fib?.direction??"LONG"} onChange={e=>setF("direction",e.target.value)} className="bg-white/5 p-2 text-xs"><option>LONG</option><option>SHORT</option></select><input value={fib?.swing_low??""} onChange={e=>setF("swing_low",e.target.value)} placeholder="swing low" className="bg-white/5 p-2 text-xs"/><input value={fib?.swing_high??""} onChange={e=>setF("swing_high",e.target.value)} placeholder="swing high" className="bg-white/5 p-2 text-xs"/></div><button onClick={()=>void saveFib()} className="mt-2 text-xs text-cyan-300">Save Fib</button>{!fib&&<span className="ml-2 text-xs text-slate-500">No Fib definition</span>}<div className="mt-4 grid grid-cols-2 gap-2"><input value={range?.range_low??""} onChange={e=>setR("range_low",e.target.value)} placeholder="range low" className="bg-white/5 p-2 text-xs"/><input value={range?.range_high??""} onChange={e=>setR("range_high",e.target.value)} placeholder="range high" className="bg-white/5 p-2 text-xs"/></div><button onClick={()=>void saveRange()} className="mt-2 text-xs text-cyan-300">Save Range</button>{!range&&<span className="ml-2 text-xs text-slate-500">No Range definition</span>}<div className="mt-2 text-xs text-amber-300">{message}</div></>:<p className="text-xs text-slate-500">Select a plan.</p>}</Panel>}
