"""add persistent trading journal

Revision ID: 4b7d594785d9
Revises:
Create Date: 2026-09-22 13:22:02.262480

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b7d594785d9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trade_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("setup_type", sa.String(length=64), nullable=False),
        sa.Column("thesis", sa.Text(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=32), nullable=False),
        sa.Column("hard_invalidation", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("thesis_warning", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("max_risk_percent", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("max_risk_value", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("correlation_group", sa.String(length=64), nullable=True),
        sa.Column("entry_probe_plan", sa.JSON(), nullable=False),
        sa.Column("add_conditions", sa.JSON(), nullable=False),
        sa.Column("target_ladder", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trade_plans_correlation_group"), "trade_plans", ["correlation_group"], unique=False
    )
    op.create_index(
        op.f("ix_trade_plans_lifecycle_status"), "trade_plans", ["lifecycle_status"], unique=False
    )
    op.create_index(op.f("ix_trade_plans_symbol"), "trade_plans", ["symbol"], unique=False)
    op.create_table(
        "decision_snapshots",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("action_considered", sa.String(length=16), nullable=False),
        sa.Column("action_taken", sa.String(length=16), nullable=True),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("evidence_present", sa.JSON(), nullable=False),
        sa.Column("evidence_missing", sa.JSON(), nullable=False),
        sa.Column("confirmation_conditions", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("data_confidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trade_plan_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trade_plan_id"], ["trade_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_snapshots_symbol"), "decision_snapshots", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_decision_snapshots_timestamp"), "decision_snapshots", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_decision_snapshots_trade_plan_id"),
        "decision_snapshots",
        ["trade_plan_id"],
        unique=False,
    )
    op.create_index(
        "ix_snapshots_plan_time", "decision_snapshots", ["trade_plan_id", "timestamp"], unique=False
    )
    op.create_table(
        "execution_rules",
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("rule_type", sa.String(length=64), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ordering", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trade_plan_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trade_plan_id"], ["trade_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_rules_trade_plan_id"), "execution_rules", ["trade_plan_id"], unique=False
    )
    op.create_table(
        "fib_definitions",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("swing_low", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("swing_high", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trade_plan_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trade_plan_id"], ["trade_plans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fib_definitions_symbol"), "fib_definitions", ["symbol"], unique=False)
    op.create_index(
        op.f("ix_fib_definitions_trade_plan_id"), "fib_definitions", ["trade_plan_id"], unique=False
    )
    op.create_table(
        "range_definitions",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("range_low", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("range_high", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trade_plan_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trade_plan_id"], ["trade_plans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_range_definitions_symbol"), "range_definitions", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_range_definitions_trade_plan_id"),
        "range_definitions",
        ["trade_plan_id"],
        unique=False,
    )
    op.create_table(
        "trade_reviews",
        sa.Column("realized_r", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("facts", sa.JSON(), nullable=False),
        sa.Column("deviations", sa.JSON(), nullable=False),
        sa.Column("lifecycle_history_complete", sa.Boolean(), nullable=True),
        sa.Column("data_confidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trade_plan_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trade_plan_id"], ["trade_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trade_plan_id", name="uq_trade_reviews_trade_plan_id"),
    )
    op.create_index(
        op.f("ix_trade_reviews_trade_plan_id"), "trade_reviews", ["trade_plan_id"], unique=False
    )
    op.create_table(
        "watched_setups",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("setup_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trade_plan_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trade_plan_id"], ["trade_plans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_watched_setups_symbol"), "watched_setups", ["symbol"], unique=False)
    op.create_index(
        op.f("ix_watched_setups_trade_plan_id"), "watched_setups", ["trade_plan_id"], unique=False
    )
    op.create_table(
        "execution_events",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=16), nullable=False),
        sa.Column("bybit_execution_id", sa.String(length=128), nullable=True),
        sa.Column("bybit_order_id", sa.String(length=128), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("position_before", sa.JSON(), nullable=False),
        sa.Column("position_after", sa.JSON(), nullable=False),
        sa.Column("risk_before", sa.JSON(), nullable=False),
        sa.Column("risk_after", sa.JSON(), nullable=False),
        sa.Column("planned", sa.Boolean(), nullable=True),
        sa.Column("confirmation_satisfied", sa.Boolean(), nullable=True),
        sa.Column("risk_policy_satisfied", sa.Boolean(), nullable=True),
        sa.Column("decision_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("confidence_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trade_plan_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_snapshot_id"],
            ["decision_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(["trade_plan_id"], ["trade_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bybit_execution_id", name="uq_execution_events_bybit_execution_id"),
    )
    op.create_index(
        "ix_events_plan_time", "execution_events", ["trade_plan_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_execution_events_symbol"), "execution_events", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_execution_events_timestamp"), "execution_events", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_execution_events_trade_plan_id"),
        "execution_events",
        ["trade_plan_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_execution_events_trade_plan_id"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_timestamp"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_symbol"), table_name="execution_events")
    op.drop_index("ix_events_plan_time", table_name="execution_events")
    op.drop_table("execution_events")
    op.drop_index(op.f("ix_watched_setups_trade_plan_id"), table_name="watched_setups")
    op.drop_index(op.f("ix_watched_setups_symbol"), table_name="watched_setups")
    op.drop_table("watched_setups")
    op.drop_index(op.f("ix_trade_reviews_trade_plan_id"), table_name="trade_reviews")
    op.drop_table("trade_reviews")
    op.drop_index(op.f("ix_range_definitions_trade_plan_id"), table_name="range_definitions")
    op.drop_index(op.f("ix_range_definitions_symbol"), table_name="range_definitions")
    op.drop_table("range_definitions")
    op.drop_index(op.f("ix_fib_definitions_trade_plan_id"), table_name="fib_definitions")
    op.drop_index(op.f("ix_fib_definitions_symbol"), table_name="fib_definitions")
    op.drop_table("fib_definitions")
    op.drop_index(op.f("ix_execution_rules_trade_plan_id"), table_name="execution_rules")
    op.drop_table("execution_rules")
    op.drop_index("ix_snapshots_plan_time", table_name="decision_snapshots")
    op.drop_index(op.f("ix_decision_snapshots_trade_plan_id"), table_name="decision_snapshots")
    op.drop_index(op.f("ix_decision_snapshots_timestamp"), table_name="decision_snapshots")
    op.drop_index(op.f("ix_decision_snapshots_symbol"), table_name="decision_snapshots")
    op.drop_table("decision_snapshots")
    op.drop_index(op.f("ix_trade_plans_symbol"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_lifecycle_status"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_correlation_group"), table_name="trade_plans")
    op.drop_table("trade_plans")
    # ### end Alembic commands ###
