"use client";
import { useCallback, useMemo, useState } from "react";
import { api } from "@/lib/api/client";
import type { ExecutionEvent, Snapshot, TradePlan, TradeReview } from "@/lib/api/types";
import { money } from "@/lib/format";
import { usePolling } from "@/lib/api/use-polling";
import { StatusBadge } from "./status-badge";
import { EmptyState, ErrorState, PageHeader, Panel } from "./ui";
type Item={id:string;time:string;type:string;title:string;detail:string;automatic?:boolean};
export function JournalClient(){const loader=useCallback(()=>api.getTradePlans(),[]);const{data,error}=usePolling(loader,30000);const[selected,setSelected]=useState<string|null>(null);const[snapshots,setSnapshots]=useState<Snapshot[]>([]);const[events,setEvents]=useState<ExecutionEvent[]>([]);const[review,setReview]=useState<TradeReview|null>(null);
 const timeline=useMemo(()=>{const items:Item[]=[...snapshots.map(s=>({id:s.id,time:s.timestamp,type:"SNAPSHOT",title:`${s.action_considered} considered`,detail:s.reason??`${money(s.price)} · ${s.evidence_missing.length} missing`,automatic:s.state?.source==="state_change_monitor"})),...events.map(e=>({id:e.id,time:e.timestamp,type:e.event_type,title:e.event_type,detail:`${e.quantity??"—"} @ ${money(e.price)} · ${e.confidence_status}`}))];if(review)items.push({id:review.id,time:review.created_at,type:"REVIEW",title:"Trade review",detail:`Realized R: ${review.realized_r??"unknown"}`});return items.sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));},[snapshots,events,review]);
 return <><PageHeader eyebrow="DECISION MEMORY" title="Journal" detail="Chronological evidence showing what was known, considered, and executed at each point in time."/>{error&&!data&&<ErrorState message={error}/>}<div className="grid gap-5 xl:grid-cols-[300px_1fr]"><Panel title="Trade plan"><select value={selected??""} onChange={e=>{const id=e.target.value||null;setSelected(id);if(id)void Promise.all([api.getSnapshots(id),api.getExecutionEvents(id),api.getTradeReview(id).catch(()=>null)]).then(([s,e,r])=>{setSnapshots(s);setEvents(e);setReview(r);});}} className="w-full rounded border border-white/10 bg-[#080b10] px-3 py-2.5 text-sm text-slate-300 outline-none focus:border-cyan-400/40"><option value="">Select a plan…</option>{data?.map((p:TradePlan)=><option key={p.id} value={p.id}>{p.symbol} · {p.setup_type} · {p.lifecycle_status}</option>)}</select><p className="mt-3 text-xs leading-5 text-slate-600">History is displayed as recorded. Missing lifecycle data is never reconstructed here.</p></Panel><Panel title="Timeline" kicker="APPEND ONLY">{!selected?<EmptyState title="Select a trade plan" detail="Snapshots, execution events, and review facts will appear in chronological order."/>:timeline.length?<div className="relative ml-2 border-l border-white/10 pl-6">{timeline.map(item=><div key={`${item.type}-${item.id}`} className="relative pb-6 last:pb-0"><span className="absolute -left-[29px] top-1.5 size-2 rounded-full bg-cyan-400 ring-4 ring-[#0d121a]"/><div className="flex flex-wrap items-center gap-2"><StatusBadge value={item.type}/>{item.automatic&&<StatusBadge value="INFO">AUTO SNAPSHOT</StatusBadge>}<span className="font-mono text-[10px] text-slate-600">{new Date(item.time).toLocaleString()}</span></div><div className="mt-2 text-sm text-slate-200">{item.title}</div><div className="mt-1 text-xs text-slate-500">{item.detail}</div></div>)}</div>:<EmptyState title="No recorded history" detail="This trade plan has no decision snapshots, execution events, or review yet."/>}</Panel></div></>}
