"use client";
import { useCallback, useState } from "react";
import { ChevronRight, RefreshCw } from "lucide-react";
import { api } from "@/lib/api/client";
import type { TradePlan } from "@/lib/api/types";
import { label, money, percent } from "@/lib/format";
import { usePolling } from "@/lib/api/use-polling";
import { StatusBadge } from "./status-badge";
import { EmptyState, ErrorState, PageHeader, Panel } from "./ui";
export function TradePlansClient(){
 const loader=useCallback(()=>api.getTradePlans(),[]); const {data,error,refresh}=usePolling(loader,30000); const [selected,setSelected]=useState<string|null>(null); const [detail,setDetail]=useState<TradePlan|null>(null);
 return <><PageHeader eyebrow="PRECOMMITTED INTENT" title="Trade Plans" detail="Read-only view of thesis, structural levels, risk limits, and predefined execution conditions." action={<button onClick={()=>void refresh()} className="flex items-center gap-2 rounded border border-white/10 px-3 py-2 text-xs text-slate-400"><RefreshCw size={13}/>Refresh</button>}/>{error&&!data&&<ErrorState message={error}/>}<div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Panel title="Plans" kicker={`${data?.length??0} RECORDS`}><div className="space-y-2">{data?.length?data.map(plan=><button key={plan.id} onClick={()=>{setSelected(plan.id);void api.getTradePlan(plan.id).then(setDetail).catch(()=>setDetail(null));}} className={`flex w-full items-center justify-between rounded border p-3 text-left ${selected===plan.id?"border-cyan-400/25 bg-cyan-400/5":"border-white/7 bg-black/10 hover:bg-white/[.025]"}`}><div><div className="flex items-center gap-2"><span className="font-semibold text-white">{plan.symbol}</span><span className="font-mono text-[9px] text-slate-500">{plan.side}</span><StatusBadge value={plan.lifecycle_status}/></div><div className="mt-1 text-xs text-slate-500">{label(plan.setup_type)} · {new Date(plan.created_at).toLocaleDateString()}</div></div><ChevronRight size={15} className="text-slate-600"/></button>):<EmptyState title="No trade plans" detail="Create plans through the explicit journal API before coaching adds."/>}</div></Panel><PlanDetail plan={detail}/></div></>;
}
function PlanDetail({plan}:{plan:TradePlan|null}){ if(!plan)return <Panel><EmptyState title="Select a trade plan" detail="Full intent and execution constraints will appear here."/></Panel>; return <Panel title={`${plan.symbol} · ${label(plan.setup_type)}`} kicker="READ ONLY"><div className="space-y-5"><div><div className="mono-label">THESIS</div><p className="mt-2 text-sm leading-6 text-slate-300">{plan.thesis}</p></div><div className="grid grid-cols-2 gap-4 md:grid-cols-4"><Fact name="INVALIDATION" value={money(plan.hard_invalidation)}/><Fact name="WARNING" value={money(plan.thesis_warning)}/><Fact name="MAX RISK" value={percent(plan.max_risk_percent)}/><Fact name="CORRELATION" value={plan.correlation_group??"—"}/></div><Section title="PREDEFINED ADD CONDITIONS" value={plan.add_conditions}/><Section title="TARGET LADDER" value={plan.target_ladder}/>{plan.execution_rules&&<Section title="EXECUTION RULES" value={plan.execution_rules}/>}</div></Panel> }
function Fact({name,value}:{name:string;value:string}){return <div><div className="mono-label">{name}</div><div className="mt-1 font-mono text-sm text-slate-200">{value}</div></div>}
function Section({title,value}:{title:string;value:unknown[]}){return <div><div className="mono-label mb-2">{title}</div>{value.length?<pre className="overflow-auto rounded border border-white/7 bg-black/20 p-3 font-mono text-[11px] leading-5 text-slate-400">{JSON.stringify(value,null,2)}</pre>:<div className="rounded border border-dashed border-white/8 p-3 text-xs text-slate-600">None defined</div>}</div>}
